set(CMAKE_CROSSCOMPILING 1)
set(CROSSCOMPILING_COMPILER gcc)
set(CROSSCOMPILING_TARGET_ARCHITECTURE x86)
set(CROSSCOMPILING_TARGET_SYSTEM linux)
set(CROSSCOMPILING_TARGET_PLATFORM i686-unknown-${CROSSCOMPILING_TARGET_SYSTEM}-musl)
set(CMAKE_SYSTEM_NAME Linux)

execute_process(
  COMMAND brew list --versions ${CROSSCOMPILING_TARGET_PLATFORM}
  OUTPUT_VARIABLE HOMEBREW_FORMULA_VERSION
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
string(REGEX REPLACE "[A-Za-z0-9_-]* ([A-Za-z0-9_-]*)" "\\1" TOOLCHAIN_VERSION "${HOMEBREW_FORMULA_VERSION}")

execute_process(
  COMMAND brew --cellar ${CROSSCOMPILING_TARGET_PLATFORM}
  OUTPUT_VARIABLE HOMEBREW_FORMULA_DIR
  OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(TOOLCHAIN_DIR ${HOMEBREW_FORMULA_DIR}/${TOOLCHAIN_VERSION})

set(CMAKE_SYSROOT ${TOOLCHAIN_DIR}/toolchain/${CROSSCOMPILING_TARGET_PLATFORM}/sysroot/)
set(CMAKE_C_COMPILER ${TOOLCHAIN_DIR}/bin/${CROSSCOMPILING_TARGET_PLATFORM}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_DIR}/bin/${CROSSCOMPILING_TARGET_PLATFORM}-g++)